### PR TITLE
Glitch

### PR DESCRIPTION
**Pull request by aliyss**

### CODE REVIEW

**Comment by Macley-Kun** [comment]
You Made a port of the project for glitch?

Would be cool to make a pull for iT ;)

**Comment by Aliyss** [comment]
Ah @Macley-Kun, yeh it works really easy though. I don't think there's a reason to create a pull.

You just import the standard files and then run node server.js in the console.

**Comment by Macley-Kun** [comment]
Mhm that's quite straight forward yeh. I've used Glitch in the past, was ok but i had some issues keeping the app up.

Maybe *if you want ofc* you could write a instruction how to do it?
Example: https://github.com/synzen/Discord.RSS/issues/45

The more ways you can host the bot, the better :D !!!

**Comment by Aliyss** [comment]
Well keeping the app up is not that hard just use https://uptimerobot.com/

I really have no time to write an Instruction at the moment, but the simple steps are

Create a Glitch account.
Import Master from GitHub
Replace BotToken in config

click on logs
click on command shell
input node server.js

Open https://uptimerobot.com/
Create free account
make UptimeRobot ping the site regularly.
Make to instances to be sure the site stays up.

for backup files:
open a new instance of the command shell
input refresh
check source folder with the new backup files.

**Pull request closed without merging**
