### PR TITLE
Translate partially es-CL

### PR DESCRIPTION
**Pull request by Monoverde888**
Sorry if it is not too big but i tried my best

### CODE REVIEW

**Comment by Monoverde888** [comment]
why did it fail

**Comment by Monoverde888** [comment]
i didnt change anything except  src/locales/es-CL.json

**Comment by synzen** [comment]
No worries about the failure, that's caused by something else. Thanks for the contribution, but unfortunately there are too few translations with only 11.76% coverage 

image

Ideally it should be 100%, or close to it - otherwise users will think that the locale switch had no effect. I can leave this PR open for now until others (or you) would like to finish the translation.

**Comment by Monoverde888** [comment]
😢

**Comment by Monoverde888** [comment]
Ok

**Pull request closed without merging**
